steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/ms-store-430722/docker-image-registry/ms-products",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/ms-store-430722/docker-image-registry/ms-products",
      ]
options:
  logging: CLOUD_LOGGING_ONLY